sudo: required
services:
  - docker

before_install:
  - docker build -t seanmoynihan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true seanmoynihan/react-test npm test

after_success:
  - docker build -t seanmoynihan/multi-client:v2 ./client
  - docker build -t seanmoynihan/multi-nginx ./nginx
  - docker build -t seanmoynihan/multi-server ./server
  - docker build -t seanmoynihan/multi-worker ./worker
  #log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login  -u "$DOCKER_ID" --password-stdin
  #push our images to docker hub
  - docker push seanmoynihan/multi-client:v2
  - docker push seanmoynihan/multi-nginx
  - docker push seanmoynihan/multi-server
  - docker push seanmoynihan/multi-worker
